### ISSUE TITLE
Using updateProperties on object properties

### ISSUE THREAD

**Issue by iberflow** [pangratz/ember-memento#10]
Would it be possible to implement another method (or extend this one) to merge properties that are object fields without replacing the whole object? e.g.

``` javascript
Editor.Element = Em.Object.extend(Editor.Memento, {
    style: {
        'border-style': 'none',
        width: '200px',
        height: '40px'
    }
});
var el = Editor.Element.create();
el.updateProperties({style: {'width':'300px','height':'200px'}}); //this should replace width and height only and leave border-style unchanged, but would push a new state into the history
```

**Comment by pangratz** [comment]
Hmm, I think this is a special use case and I don't think if this should be supported in the API. Declaring `style` as an `Ember.Object(Ember.Memento, {...})` is out of question?

**Comment by iberflow** [comment]
I'm afraid yes, because I don't want to change the whole app's structure just to implement this. I only need the style property to act this way and the other object attributes would work as normal. I'm thinking maybe I could make a new method for my case just to update the style property in which I could somehow loop through the passed object and update the style with setPath or something, but how would I prevent the observers from firing? I would appreciate a hand on this

**Comment by iberflow** [comment]
Solved it with this:

```
updateStyle: function(hash) {
        var style = this.get('style');
        for (var prop in hash) {
            if (hash.hasOwnProperty(prop)) {
                style[prop] = hash[prop];
            }
        }
        this.set('style', _.clone(style));
    },
```

**Comment by pangratz** [comment]
Glad you've got it working! Thanks for posting your solution.
