### ISSUE TITLE
ember data integration

### ISSUE THREAD

**Issue by ddemolina** [pangratz/ember-memento#13]
Hi,
Is there a way to integrate it with ember data?

Thanks

**Comment by pangratz** [comment]
I haven't tested it with ember-data and I wouldn't recommend this mixin anymore since it hasn't been updated in a while.

If you need an up-to-date addon which does this kind of stuff, I recommend to use [yapplabs/ember-buffered-proxy](https://github.com/yapplabs/ember-buffered-proxy)...
